language: ruby
rvm:
  - "2.0.0"
  # - "1.9.3"
env:
  # - DB=postgresql
  - DB=postgres
before_script:
  - psql -c 'create database portfoliotest;' -U postgres
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake
bundler_args: --binstubs=./bundler_stubs
