language: ruby
rvm:
- 2.0.0
env:
- DB=postgres
before_script:
- psql -c 'create database db/portfolio_test;' -U postgres
script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake
bundler_args: --binstubs=./bundler_stubs
deploy:
  provider: heroku
  api_key:
    secure: RVoJVSJ2smDH1lWS7UZrrz7J1jMTE6O8fRZc73tpbMlXv8BxDZbuYmmGgrrFLxVK9Z/wy8T4iOFjJkMf/Z2oXvtJx3ZS+3Rkm+0Tj/AXMzkfFbDVu81/qI4qYShogyDizzKEKLVMAuQ8Btxfwng31kgtnvZ7ryjmigyU9Wubd4w=
  app: sprestage-portfolio
  on:
    repo: sprestage/Portfolio
