language: ruby
rvm:
  - 2.2.1
env:
  - DB=postgres
before_script:
  - psql -c 'create database portfolio_test;' -U postgres

deploy:
  provider: heroku
  api_key:
    secure: jtqJadkYVUf17mjRGdMpFOZMr0CDauXYrFyodQ7pkVKSAMfDaHZ0EcIp95xaTk0H0BPOQVWbobkThFgzTJusvkF8DGtMpmaKVMqU+AXthqGb9L1Iz+Nv93S4y98Oeyg/m0fqBj6RsiZ8H+T3HiVr8gXuSXqwUEJyb/gDk2FN8Ek=
  app: new-sprestage-portfolio
  on:
    repo: sprestage/Portfolio
run:
  - rake db:migrate
  - rake db:fixtures:load
