language: ruby
rvm:
- 2.2.1
env:
- DB=postgres
before_script:
- psql -c 'create database portfolio_test;' -U postgres
run:
- rake db:migrate
- rake db:fixtures:load
deploy:
  provider: heroku
  api_key:
    secure: LoFBE9Wz9SsrJ3pMyVsQIf3T7vdlfvWDu/9h5qIoogi/QFyBtY8NPAQn7zSVlajU5mLdR8ngVNUHpoo4MXUvr9G2m0RhBUM1wUXxkFHSYY5W01BhItOj1oDu/LvMqtTH5bvo07MnuCYD0Wa+XlXucuJS2INW2eip1p0+HIAz8zQ=
  app: sprestage-portfolio
  on:
    repo: sprestage/Portfolio
